language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install: pip install poetry tox tox-travis codecov
script: tox --recreate
after_success:
  - codecov
jobs:
  include:
    - stage: release
      if: branch = master
      python: "3.8"
      script: skip # Skip the tests this time
      deploy:
        provider: script
        script: poetry install && poetry run python release.py --publish
