name: build

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9] # "pypy-3.7" not included due to https://github.com/python/typed_ast/issues/126
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry and Tox
        run: pip install poetry==1.1.6 tox==3.23.1
      - name: Run Tox
        run: tox -e py -e flake8
      - name: Install coverage.py globally so that codecov can find it
        run: pip install coverage==5.2
      - uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: test
    if: github.repository_owner == 'bjoluc' && github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install poetry
        run: pip install poetry==1.1.6
      - uses: bjoluc/semantic-release-config-poetry@v1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
